# John Hurst (john.b.hurst@gmail.com)
# 2023-06-10

stages:
  split_tones:
    cmd: bin/split_tones.py data/raw_voices/*
    deps:
      - data/raw_voices/
      - bin/split_tones.py
    outs:
      - data/raw_tones/:
          cache: false

  voice_stats:
    cmd: bin/voice_stats.py data/raw_tones/*
    deps:
      - data/raw_tones/
      - bin/voice_stats.py
    outs:
      - data/voice_stats/:
          cache: false
