# John Hurst (john.b.hurst@gmail.com)
# 2023-06-10

stages:
  split_tones:
    cmd: bin/split_tones.py data/raw_voices/*
    deps:
      - data/raw_voices/
      - bin/split_tones.py
    outs:
      - data/raw_tones/:
          cache: false

  voice_stats:
    cmd: bin/voice_stats.py data/raw_tones/*
    deps:
      - data/raw_tones/
      - bin/voice_stats.py
    outs:
      - data/voice_stats/:
          cache: false

  tone_waveforms:
    cmd: bin/tone_waveforms.py data/raw_tones/*
    deps:
      - data/raw_tones/
      - bin/tone_waveforms.py
    outs:
      - data/tone_waveforms/:
          cache: false

  voice_reports:
    cmd: bin/voice_reports.py data/tone_waveforms/Voice_*
    deps:
      - data/tone_waveforms/
      - bin/voice_reports.py
    outs:
      - data/reports/voice_reports/:
          cache: false

  tone_reports:
    cmd: bin/tone_reports.py data/tone_waveforms/Voice_*
    deps:
      - data/tone_waveforms/
      - bin/tone_reports.py
    outs:
      - data/reports/tone_reports/:
          cache: false
